name: Shell Commands

on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:

      - name: echo a string
        run: echo "Hey Justin"
      
      - name: Run multiline script
        run: |
          node -v
          npm -v 
  
